---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: speedtest
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nicholaswilde.io
spec:
  rules:
    - host: st.nicholaswilde.io
      http:
        paths:
          - backend:
              serviceName: speedtest
              servicePort: 8080
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
spec:
  type: ClusterIP
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: speedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
        # This is the only image they have..
        - image: openspeedtest/latest:speedtest
          name: speedtest
          env:
          ports:
            - containerPort: 8080
              name: speedtest
