---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: managed-nfs-storage
  namespace: flux-system
spec:
  chart:
    spec:
      # yamllint disable-line rule:line-length
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      version: 4.0.12
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
  interval: 30s
  targetNamespace: managed-nfs-storage
  values:
    nfs:
      path: /home/pi/nas/nfs
      server: 192.168.1.192
    storageClass:
      defaultClass: true
      name: managed-nfs-storage
      reclaimPolicy: Retain
