---
- name: cluster | kubeconfig | copy config file to /tmp
  become: true
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "~/.kube/config-turing-pi"
    flat: true
  when:
    - k3s_control_node is defined
    - k3s_control_node

- name: cluster | kubeconfig | update kubeconfig with the right IPv4 address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "~/.kube/config-turing-pi"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ k3s_registration_address }}:6443'
