---
- name: metallb | deploy namespace to k3s manifest directory
  become: true
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/metallb/metallb/{{ metallb.version }}/manifests/namespace.yaml'
    dest: '{{ k3s_server_manifests_dir }}/metallb-namespace.yaml'
    mode: 0644

- name: metallb | deploy resources to k3s manifest directory
  become: true
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/metallb/metallb/{{ metallb.version }}/manifests/metallb.yaml'
    dest: "{{ k3s_server_manifests_dir }}/metallb.yaml"
    mode: 0644

- name: metallb | deploy configmap to k3s manifest directory
  become: true
  ansible.builtin.template:
    src: "metallb-configmap.j2"
    dest: "{{ k3s_server_manifests_dir }}/metallb-configmap.yaml"
    mode: 0644

- name: metallb | create secret
  shell: openssl rand -base64 128 | tr -d '\n\r'
  register: command_output

- set_fact:
    secret: "{{ command_output.stdout }}"

- name: metallb | deploy secret to k3s manifest directory
  become: true
  ansible.builtin.copy:
    dest: "{{ k3s_server_manifests_dir }}/metallb-secret.yaml"
    mode: 0644
    content: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      data:
        secretkey: '{{ command_output.stdout | trim }}'
