---
version: '3'

tasks:
  build:
    desc: Build documentation using Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/docs --platform linux/amd64
        squidfunk/mkdocs-material build -f ./mkdocs.yml

  serve:
    desc: Serve the mkdocs site.
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT }} -v ${PWD}:/docs
        --platform linux/amd64 squidfunk/mkdocs-material serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
    deps:
      - task: build
    vars:
      PORT: 8000
