---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/server/ansible"
  TZ: "America/Los_Angeles"

includes:
  ansible: ./.taskfiles/ansible.yaml
  blocky: ./.taskfiles/blocky.yaml
  cert: ./.taskfiles/cert.yaml
  docs: ./.taskfiles/docs.yaml
  flux: ./.taskfiles/flux.yaml
  gpg: ./.taskfiles/gpg.yaml
  hr: ./.taskfiles/hr.yaml
  k3s: ./.taskfiles/k3s.yaml
  lint: ./.taskfiles/lint.yaml
  mkdocs: ./.taskfiles/mkdocs.yaml
  ns: ./.taskfiles/ns.yaml
  values: ./.taskfiles/values.yaml

tasks:
  bootstrap:
    desc: Bootstrap the entire cluster
    cmds:
      - task: "ansible:prepare"
      - task: "ansible:install"
      - task: "k3s:private"
      - task: "k3s:flux"

  lint:
    desc: Lint the files
    cmds:
      - task: lint:yamllint
      - task: lint:markdownlint
      - task: lint:linkcheck
      - task: lint:shellcheck

  default:
    cmds:
      - task -l
    silent: true
