---
version: '3'

tasks:
  lint:
    desc: Lint the files
    cmds:
      - yamllint .
  serve:
    desc: Serve the mkdocs site.
    cmds:
      - mkdocs serve

  default:
    cmds:
      - task -l
    silent: true
