---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/server/ansible"

includes:
  ansible: ./.taskfiles/ansible.yaml
  ns: ./.taskfiles/ns.yaml
  lint: ./.taskfiles/lint.yaml
  gpg: ./.taskfiles/gpg.yaml
  mkdocs: ./.taskfiles/mkdocs.yaml
  docs: ./.taskfiles/docs.yaml

tasks:
  lint:
    desc: Lint the files
    cmds:
      - task: lint:yamllint
      - task: lint:markdownlint
      - task: lint:linkcheck

  default:
    cmds:
      - task -l
    silent: true
