---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
  interval: 1m0s
  targetNamespace: media
  values:
    nextcloud:
      host: n.nicholaswilde.io
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: nicholaswilde.io
    persistence:
      enabled: true
      storageClass: "managed-nfs-storage"
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
