---
- name: packages | disable recommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/02norecommends
    mode: 0644
    create: true
    block: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";

- name: packages | upgrade all packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  when:
    - >-
      (skip_upgrade_packages is not defined or
      (skip_upgrade_packages is defined and not skip_upgrade_packages))

- name: packages | install common
  ansible.builtin.apt:
    name: "{{ packages.apt_install }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
  when:
    - packages.apt_install is defined
    - packages.apt_install is iterable
    - packages.apt_install | length > 0

- name: packages | remove crufty packages
  block:

    - name: packages | remove crufty packages | gather install packages
      ansible.builtin.package_facts:
        manager: auto
      when:
        - "'snapd' in packages.apt_remove"

    - name: packages | remove crufty packages | check if snap is installed
      ansible.builtin.debug:
        msg: "snapd is installed"
      register: snapd_check
      when:
        - "'snapd' in packages.apt_remove"
        - "'snapd' in ansible_facts.packages"

    - name: packages | remove crufty packages | remove snap packages
      ansible.builtin.command: snap remove {{ item }}
      loop:
        - lxd
        - core18
        - snapd
      when:
        - "'snapd' in packages.apt_remove"
        - "'snapd' in ansible_facts.packages"
        - snapd_check.failed is defined

    - name: packages | remove crufty packages | remove packages
      ansible.builtin.apt:
        name: "{{ packages.apt_remove }}"
        state: absent
        autoremove: true

    - name: packages | remove crufty packages | remove crufty files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/home/{{ ansible_user }}/.snap"
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
        - "/etc/cloud"
        - "/var/lib/cloud"
      when:
        - "'snapd' in packages.apt_remove"
        - "'cloud-init' in packages.apt_remove"
  when:
    - packages.apt_remove is defined
    - packages.apt_remove is iterable
    - packages.apt_remove | length > 0
    - >-
      (skip_remove_packages is not defined or
      (skip_remove_packages is defined and not skip_remove_packages))
