---
# Timezone for the servers
timezone: "America/Los_Angeles"

k3s_server:
  node-ip: "{{ ansible_host }}"
k3s_release_version: "v1.19.9+k3s1"

# Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to use hard
# links rather than symbolic links as the controller will not be able to
# follow symbolic links.
k3s_install_hard_links: true

# Escalate user privileges for all tasks.
k3s_become_for_all: true

# Use experimental features (spooky!)
k3s_use_experimental: false

# Enable debugging
k3s_debug: false
k3s_etcd_datastore: true

# Enable rsyslog
# ...requires a rsyslog server already set up
rsyslog:
  enabled: false
  ip: 192.168.1.192
  port: 1514
