---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "unifi-certificate"
  namespace: cert-manager
spec:
  secretName: "unifi-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "unifi.nicholaswilde.io"
  dnsNames:
    - "unifi.nicholaswilde.io"
