---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts/
      chart: transmission
      version: 0.2.17
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde-charts
  interval: 30s
  targetNamespace: media
  values:
    env:
      TRANSMISSION_WEB_HOME: /kettu/
      TZ: America/Los_Angeles
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/linuxserver/transmission
      tag: 3.00-r2-ls81
    ingress:
      enabled: true
      hosts:
        - host: transmission.192.168.1.201.nip.io
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        accessMode: ReadWriteOnce
        emptyDir: false
        enabled: true
        mountPath: /config
        size: 1Gi
        skipuninstall: false
        storageClass: managed-nfs-storage
      downloads:
        accessMode: ReadWriteOnce
        emptyDir: false
        enabled: true
        mountPath: /downloads
        size: 1Gi
        skipuninstall: false
        storageClass: managed-nfs-storage
      watch:
        accessMode: ReadWriteOnce
        emptyDir: false
        enabled: true
        mountPath: /watch
        size: 1Gi
        skipuninstall: false
        storageClass: managed-nfs-storage
    secret:
      pass: hypriot
      user: pirate
    service:
      additionalPorts:
        - name: 51413-tcp
          port: 51413
        - name: 51413-udp
          port: 51413
          protocol: UDP
      port:
        port: 9091
    strategy:
      type: Recreate
