---
- hosts: cluster
  gather_facts: true
  become: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  environment:
    K8S_AUTH_KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  roles:
    - role: xanmanning.k3s
      tags: ["install"]
    - role: k3s
      tags: ["k3s"]
