---
- hosts: cluster
  gather_facts: true
  become: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - role: install/cluster

- hosts: main
  become: true
  roles:
    - role: install/main

- hosts: node
  become: true
  roles:
    - role: install/node
