---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: flux-system
spec:
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: twuni-charts
      version: 1.10.1
  interval: 1m0s
  targetNamespace: media
  values:
    ingress:
      enabled: true
      hosts:
        - registry.192.168.1.205.nip.io
      path: /
      tls:
        - secretName: traefik-cert
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    storage: filesystem
    persistence:
      accessMode: 'ReadWriteOnce'
      enabled: true
      storageClass: 'managed-nfs-storage'
