---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: flux-system
spec:
  chart:
    spec:
      chart: blocky
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
  interval: 1m0s
  targetNamespace: kube-system
  values:
    config: |
      upstream:
        externalResolvers:
          - tcp-tls:4838af.dns1.nextdns.io:853
          - tcp-tls:4838af.dns2.nextdns.io:853
      blocking:
        blackLists:
          ads:
            # https://oisd.nl/
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: udp:192.168.1.1
    env:
      TZ: America/Los_Angeles
    image:
      repository: spx01/blocky
      tag: v0.13
