---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
  interval: 1m0s
  targetNamespace: kube-system
  values:
    config: |
      upstream:
        externalResolvers:
          - tcp-tls:4838af.dns1.nextdns.io:853
          - tcp-tls:4838af.dns2.nextdns.io:853
          - tcp+udp:8.8.8.8
          - tcp+udp:8.8.4.4
          - tcp+udp:1.1.1.1
          - tcp-tls:1.0.0.1:853
          - https://cloudflare-dns.com/dns-query
      blocking:
        blackLists:
          ads:
            # https://oisd.nl/
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: udp:192.168.1.1
    env:
      TZ: America/Los_Angeles
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.13
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 250Mi
    service:
      additionalServices:
        - enabled: true
          externalIPs:
            - 192.168.1.202
          externalTrafficPolicy: Local
          nameSuffix: dns-tcp
          port:
            name: dns-tcp
            port: 53
            protocol: TCP
            targetPort: 53
          type: LoadBalancer
        - enabled: true
          externalIPs:
            - 192.168.1.202
          externalTrafficPolicy: Local
          nameSuffix: dns-udp
          port:
            name: dns-udp
            port: 53
            protocol: UDP
            targetPort: 53
          type: LoadBalancer
