---
- name: filesystem | sysctl | update max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

# - name: filesystem | swap | disable at runtime
  # ansible.builtin.command: swapoff -a
  # when: ansible_swaptotal_mb > 0

# - name: filesystem | swap | disable on boot
  # ansible.posix.mount:
    # name: "{{ item }}"
    # fstype: swap
    # state: absent
  # loop:
    # - swap
    # - none
