---
- include: host.yaml
  tags: ["host"]

- include: locale.yaml
  tags: ["locale"]

- include: packages.yaml
  tags: ["packages"]

- include: filesystem.yaml
  tags: ["filesystem"]

- include: unattended-upgrades.yaml
  tags: ["unattended-upgrades"]

- include: journald.yaml
  tags: ["journald"]

- include: user.yaml
  tags: ["user"]

- include: rpi.yaml
  tags: ["rpi"]

- include: rsyslog.yml
  when:
    - rsyslog.enabled is defined
    - rsyslog.enabled
  tags: ["rsyslog"]

- include: swap.yaml
  tags: ["swap"]
