---
- name: packages | disable recommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/02norecommends
    mode: 0644
    create: true
    block: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";

- name: packages | upgrade all packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  when:
    - >
      (skip_upgrade_packages is not defined or
      (skip_upgrade_packages is defined and not skip_upgrade_packages))

- name: packages | install common
  ansible.builtin.apt:
    name: "{{ packages.apt_install }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
  when:
    - packages.apt_install is defined
    - packages.apt_install is iterable
    - packages.apt_install | length > 0

- name: packages | remove crufty packages | remove packages
  ansible.builtin.apt:
    name: "{{ packages.apt_remove }}"
    state: absent
    autoremove: true
  when:
    - packages.apt_remove is defined
    - packages.apt_remove is iterable
    - packages.apt_remove | length > 0

- name: packages | run autoremove
  ansible.builtin.apt:
    autoremove: true
