---
- name: rsyslog
  block:
  - name: rsyslog | copy promtail configuration
    ansible.builtin.template:
      src: "rsyslog-50-promtail.conf.j2"
      dest: "/etc/rsyslog.d/50-promtail.conf"
      mode: 0644
  - name: rsyslog | start systemd service
    ansible.builtin.systemd:
      name: rsyslog
      enabled: true
      state: started
  - name: rsyslog | restart systemd service
    ansible.builtin.systemd:
      name: rsyslog.service
      daemon_reload: true
      enabled: true
      state: restarted
