---
- name: unattended-upgrades | copy 20auto-upgrades config
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    create: true
    block: |
      APT::Periodic::Update-Package-Lists "14";
      APT::Periodic::Download-Upgradeable-Packages "14";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";

- name: unattended-upgrades | copy 50unattended-upgrades config
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    create: true
    block: |
      Unattended-Upgrade::Automatic-Reboot "false";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}";
          "${distro_id} ${distro_codename}-security";
      };

- name: unattended-upgrades | start systemd service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: unattended-upgrades | restart systemd service
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
