---
- name: user | get home directory
  ansible.builtin.shell: "echo $HOME"
  changed_when: false
  check_mode: false
  register: user_home

- name: user | add to sudoers
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"

- name: user | check if hushlogin exists
  ansible.builtin.stat:
    path: "~{{ ansible_user }}/.hushlogin"
  register: hushlogin_result

- name: user | silence the login prompt
  ansible.builtin.file:
    dest: "~{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
  when: not hushlogin_result.stat.exists

- name: user | check if sshpwd.sh exists
  ansible.builtin.stat:
    path: "/etc/profile.d/sshpwd.sh"
  register: password_result

- name: user | remove default password warning
  ansible.builtin.file:
    path: "/etc/profile.d/sshpwd.sh"
    state: absent
  when: password_result.stat.exists
