---
all:
  children:
    rpis:
      hosts:
        pi-w:
          ansible_host: 192.168.1.29
        pi-02:
          ansible_host: 192.168.1.250
        pi-04:
          ansible_host: 192.168.1.192
      vars:
        ansible_user: pi
