---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: managed-nfs-storage
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
