---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: managed-nfs-storage
  namespace: managed-nfs-storage
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: managed-nfs-storage
  namespace: managed-nfs-storage
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: HelmRepository
        name: nfs
  interval: 30s
  targetNamespace: managed-nfs-storage
  values:
    nfs:
      path: /home/pi/nas/nfs
      server: 192.168.1.192
    storageClass:
      defaultClass: false
      name: managed-nfs-storage

