---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: managed-nfs-storage
  namespace: managed-nfs-storage
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
  interval: 30s
  targetNamespace: managed-nfs-storage
  values:
    nfs:
      path: /home/pi/nas/nfs
      server: 192.168.1.192
    storageClass:
      defaultClass: true
      name: managed-nfs-storage

