apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:4D/+1FIbMPLZjrSh4HM7g3ErDRpq2R3Lg1z3sow6DgWZUDqRH5YUfDs/mHYJ6PMZHfZJ4iLmZgkag/UiSyrVKbJpwfi077PbYK07XSCVRBoOjjfROJ3lhrezoruxyKTOURqi1jDqDnTC7TPjxitegtkMlAipAkP0BJAjBvT6wB6MJ7oczcScC+4Er3EDWvzNZV3ubtexspQ4d5KZIUyT1T4bD1DF1lEhGy/yqgOEc8/Vp9+nFZyo8q5iWGLvodxvVFVCoOF4qKo2p+dz/4M5TNPqslqa0btNye7unxQJEXsCbzRyNk6WIA==,iv:ITphLurDpYTRCwQgVH+/eLIvS5jFQkFfwYiWuGW0Tq0=,tag:GR/Glbix/P0iToesWVoCIA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: memberlist
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-19T20:33:13Z"
    mac: ENC[AES256_GCM,data:92maRevcVu/+Xpwaa/tQNxbtQiTliNSIrQEHrYbWrJsPg8nW38SZsG4M+J/2HyOZPzg9s/+OC0nZqly2ii9b2+SWr4VdqcJQ6zV3I4ijICxtRhEKpdjpI1zRc8bynadk6vPEvoFSZ5gmJeoEiLJHiEos6F7W7mnGZ9GilFk5MYg=,iv:ONZSZvwNYZTqM37K0i5I1VwVsBaPPIAVjT1N1+4jz9U=,tag:wWkQPxpbdeTusfsikM8Djw==,type:str]
    pgp:
        - created_at: "2021-04-19T20:33:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4NyAfFp/QIUARAAwIwnNljIC4ezCZW872S5ckvd2oHudTsQXUS7lyCTva5k
            8ov+VFNpyQhYW4+P9JXmqim3zQH1h31+2AyNb2imTtR60cwTTFmxb5V6x+dTYEd7
            DwImymepiTbVxR2kcn6zpncONsVKj248pRQyw/tWSH5NkifG0m97hzXSBSnKquWi
            oltXtnZmeaZHNnaJWxkr8BIY6JE3SR/j5Z6El+143j9/gV7GfAb/GXyTi9Cq3SvV
            fLaBJKPRkJYsFUF7+0pQqpM1rdIxp14CyBTgkgxlEb6tkqhEgIMX1k3kb3JAu79+
            19yvRX9MlZdBDzSuI1W/MLoLqbyVcZ7fPpb2EpwqQMfxwtozf+G59FLSLjx2CyQE
            Ag3lvrijW7MhpMTo4WNCJORWmgPGRyqGso+g6Ml51Iz8ujmUWF/QZYLowb64PVSt
            vWNoiWShclgQzy0Cp8wY/vPN49OxsXCbhcd+X3Xa8sOsnMYleiooc80P2xU2YZLq
            4eJxH1AMi8BLmJ7Qg57whowuz5LMSFmq/6n+ZqDy3YH/0NC3Gcu7V0NIriOTvb5M
            Ups25aiLnx+LVP0AYU/NY47VAFEcMaKEBnNOK2TcR9YraVH3JI7L6D35HWFQ5ihL
            lRnJoVboDqgHHUL6F5YB+k7RwNiBCbHl1v9GOo1ramyBLJmW4SLoTIMpojCPMRnS
            XgH03TxAv8xm/az/nUncHLWpyPyC/QkJAD0bpjPOMNwVVs5zVXZfVfwpBVLGwUk+
            thCF9BnPJ3af+99pG/87Qj2w3Vma3PubcLNxORm786U/Jkhw3ttLp3zTuzDRe84=
            =S36u
            -----END PGP MESSAGE-----
          fp: B52E4BE7765AFEDC5A3A6DDEF640C24F06992490
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
