---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-sigs-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/descheduler
