image:
  repository: ghcr.io/nicholaswilde/installer
  pullPolicy: IfNotPresent
  tag: "0.2.9-ls3"

service:
  port:
    port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "installer.192.168.1.199.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
