---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
  interval: 10m
  targetNamespace: ingress-nginx
  values:
    resources:
      limits:
        cpu: 100m
        memory: 90Mi
