---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - home.yaml
  - managed-nfs-storage.yaml
  - media.yaml
  - networking.yaml
  - system-upgrade.yaml
